# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Add PR to project
on:
  issues:
    types:
      - opened
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to Project
        uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/sarahetterorg/projects/1
          github-token: ${{ secrets.MY_PAT }}
